version: '3'

services:
  dev:
    container_name: aleph-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    # command: deno run -A https://raw.githubusercontent.com/alephjs/aleph.js/master/cli.ts dev --hostname 0.0.0.0 --port 8080
