FROM docker.pkg.github.com/jupegarnica/aleph-deno/aleph-base:latest


WORKDIR /app


RUN deno cache https://deno.land/x/aleph@v0.3.0-alpha.8/deps.ts
RUN deno cache https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts
# RUN deno cache https://deno.land/x/aleph@v0.3.0-alpha.8/cli/start.ts
# RUN deno cache https://esm.sh/react@17.0.1

EXPOSE 8080

CMD  aleph start --hostname 0.0.0.0 --port 8080