FROM ubuntu:focal
RUN apt update
RUN apt install curl -y
RUN apt install unzip -y
RUN curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh -s v1.7.2
RUN deno install -A -f -n aleph https://deno.land/x/aleph@v0.3.0-alpha.21/cli.ts
RUN export PATH="/root/.deno/bin:$PATH"
RUN /root/.deno/bin/aleph -v

WORKDIR /app


# RUN deno cache https://deno.land/x/aleph@v0.3.0-alpha.21/cli/dev.ts
# RUN deno cache https://deno.land/x/aleph@v0.3.0-alpha.21/cli/start.ts
# RUN deno cache https://deno.land/x/aleph@v0.3.0-alpha.21/deps.ts
# RUN deno cache https://esm.sh/react@17.0.1
# RUN deno cache https://deno.land/std@0.88.0/http/file_server.ts

EXPOSE 8080

CMD  /root/.deno/bin/aleph dev --hostname 0.0.0.0 --port 8080