name: build and publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*


  # BUILD_MODE: development

jobs:
  publish:

    runs-on: ubuntu-latest
    # if: github.event_name == 'push'
    steps:

      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          # docker system prune --all --force
          docker pull docker.pkg.github.com/jupegarnica/aleph-deno/aleph-base
          sh scripts/build.sh


      - name: Push image
        env:
          IMAGE_NAME: aleph-prod
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: sh scripts/publish-prod-image.sh

      - name: push latestBuild
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'add latestBuild'
          force-add: 'true'
          files: metadata/*
          name:  publish-job
          rebase: 'true'
