name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build and publish"]
    # branches: [master]
    types:
      - completed
      # - requested
env:
  LAST_BUILD:
jobs:

  setLastBuild:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - id: lastBuild
        name: set last build env
        run: |
          LAST_BUILD='cat lastBuild'
          echo "::set-env name=LAST_BUILD::$LAST_BUILD"

  deploy:
    runs-on: ubuntu-latest
    needs: setLastBuild
    steps:
      - run: echo ${{env.LAST_BUILD}}

    # - name: ls -a via ssh
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: echo ${{needs.setLastBuild.outputs.LAST_BUILD}}
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASS }}
      #     # privateKey: ${{ secrets.SSH_KEY}}
