name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build and publish"]
    # branches: [master]
    types:
      - completed
      # - requested
env:
  LAST_BUILD:
jobs:

  setLatestBuild:

    runs-on: ubuntu-latest
    outputs:
      LATEST_BUILD: ${{ steps.latestBuild.outputs.latestBuild }}
    steps:

      - uses: actions/checkout@v2
      - id: latestBuild
        name: set last build env
        run: |
          LATEST_BUILD=`cat latestBuild`
          echo $LATEST_BUILD
          echo "::set-output name=latestBuild::$LATEST_BUILD"

  deploy:
    runs-on: ubuntu-latest
    needs: setLatestBuild
    steps:
      - run: echo ${{needs.setLatestBuild.outputs.LATEST_BUILD}}

    # - name: ls -a via ssh
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: echo ${{needs.setLatestBuild.outputs.LAST_BUILD}}
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASS }}
      #     # privateKey: ${{ secrets.SSH_KEY}}
