name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build and publish"]
    # branches: [master]
    types:
      - completed
      # - requested

jobs:

  deploy:

    runs-on: ubuntu-latest
    outputs:
      LAST_BUILD: ${{ steps.lastBuild.outputs.lastBuild }}
    steps:

      - uses: actions/checkout@v2
      - id: lastBuild
        name: set last build env
        run: echo "::set-output name=lastBuild::hello"
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: echo ${{needs.deploy.outputs.LAST_BUILD}}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          # privateKey: ${{ secrets.SSH_KEY}}
