name: Test production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
jobs:

  end2end:

    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/jupegarnica/aleph-deno/aleph-test:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /home/runner/work/aleph-deno/aleph-deno/:/app
    steps:
      - run: ls -al /app
      - uses: actions/checkout@v2
      - run: sh scripts/test.sh
